### ISSUE TITLE
Make it easy for corp-semantic-release to update other source files with the new version number

### ISSUE THREAD

**Issue by uglow** [leonardoanalista/corp-semantic-release#26]
Currently the `--pre-commit <script>` flag supports calling an NPM script before commiting changes back to git. But as a user, I don't know what the new version number is or whether `package.json` has been updated with the new version already.

I see two main use-cases for the existing option: 
1. Run an NPM script which is unrelated to the new version number
2. Run an NPM script which requires the  new version number

For the second case, typically you want the new version number so that you can update other files.

So I propose:
- passing the new version number as an argument to the `--pre-commit <script>`
- writing a *new* NPM module which can be figured to parse a file which contains user-defined configuration for replacing the version number in files:

updateVersion.yml:
``` yaml
process: 
  - name: path/file.ext
    searchRE: /^version:.*$/m
    replacement: `version: ${version}`
  - name: path/file2.ext
    searchRE: /^id:.*$/m
    replacement: `id: ${version}`
```

package.json
``` json
  "scripts": {
    "release": "corp-semantic-release --pre-commit updateVersions",
    "updateVersions": "newFileUpdatingModuleWhichReceivesTheNewVersionNumber updateVersion.yml"
  }
  
  ...
  "devDependencies": {
    "newFileUpdatingModuleWhichReceivesTheNewVersionNumber": "1.0.0"
  }
```
